create table items as
select i.item_id,name, item_description, stat_1, stat_2 from items1 i
join items2 
using(item_id) ;

insert into items1 
values(1,'B.F. Sword', null, 1),
(2,'Recurve Bow', null, 1),
(3,'Needlessly Large Rod', null, 1),
(4,'Tear of the Goddess', null, 1),
(5,'Chain Vest', null, 1),
(6,'Negatron Cloak', null, 1),
(7,"Giant's Belt", null, 1),
(8,'Spatula','You will get a special ability', 1),
(9,'Sparring Gloves', null, 1),
(11,'Deathblade','Contributing to a kill grants +25 Attack Damage for the remainder of combat. This effect can stack any number of times (starting at 2).',0),
(12,'Giant Slayer',"Holder’s basic attacks and spells do 20% bonus true damage. This increases to 80% if target has >1500 current HP",0),
(13,'Hextech Gunblade','Heal for 35% of spell damage dealt',0),
(14,'Spear of Shojin','After casting wearer gains 18% of its max Mana per attack',0),
(15,'Guardian Angel','Wearer revives with 400 HP',0),
(16,'Bloodthirster','Basic Attacks heal the wearer for 35% of the damage dealt',0),
(17,"Zeke's Herald",'When combat begins the wearer and all allies within 1 hex in the same row gain +30% Attack Speed for the rest of combat',0),
(18,'Blade of the Ruined King','Wearer is also a Blademaster',0),
(19,'Infinity Edge','[Unique] The holder gains 20% bonus critical strike damage and 100% critical hit chance',0),
(22,'Rapid Firecannon','Attack Range is tripled and attacks cannot miss',0),
(23,"Guinsoo's Rageblade",'Basic Attacks grant +5% bonus Attack Speed for the rest of combat. No stacking limit.',0),
(24,'Statikk Shiv','Every third Basic Attack from the wearer deals 75 magic damage to 3/4/5 enemies',0),
(25,"Titan's Resolve",'When the wearer takes damage or inflicts a critical hit they gain a 2% stacking damage bonus. Stacks up to 50 times  at which point the wearer gains 25 Armor and Magic Resistance and increases in size.',0),
(26,"Runaan's Hurricane","Basic Attacks fire a bolt at another nearby enemy dealing 70% of the wearer's Attack Damage and applying on-hit effects",0),
(27,"Zz'Rot Portal",'When the wearer dies a Construct with 1000/2000/3000 Health aries to continue the fight',0),
(28,"Infiltrator's Talons",'The wearer gains the Infiltrator trait',0),
(29,'Last Whisper',"Critical hits reduce the target’s Armor by 90% for 3 seconds. This effect does not stack.",0),
(33,"Rabadon's Deathcap","Wearer's Spell Power stat is amplified by 50%",0),
(34,"Luden's Echo",'When the wearer casts their spell the first target dealt magic damage and up to 3 nearby enemies are dealt an additional 200 magic damage',0),
(35,'Locket of the Iron Solari',"Shields allies within two hexes in the same row for 250 / 275 / 350 damage for 8 seconds (scales with wearer's Star Level)",0),
(36,'Ionic Spark','Enemies within 2 hexes have their Magic Resist reduced by 50% (does not stack). When they cast a spell they are zapped taking magic damage equal to 225% of their max Mana',0),
(37,'Morellonomicon',"When the wearer deals damage with their spell they burn the target dealing 30% of the target's Maximum Health as true damage over 10 seconds and reducing healing by 50% for the duration of the burn",0),
(38,'Battlecast Armor','The wearer gains the Battlecast trait',0),
(39,'Jeweled Gauntlet',"Holder’s spells can crit and holder gains +20% Critical Strike Damage",0),
(44,'Blue Buff',"[Unique] Sets wearer's mana to 20 after spellcast",0),
(45,'Frozen Heart','Adjacent enemies lose 50% Attack Speed. (Stacking increases the radius of this effect not the amount of the slow)',0),
(46,'Chalice of Power','At start of combat the holder and their left and right neighbors gain 30 AP for 20 seconds',0),
(47,'Redemption','When the wearer dies allies are healed for 800 Health',0),
(48,"Star Guardian's Charm",'The wearer gains the Star Guardian trait',0),
(49,'Hand of Justice','Each planning phase gain one: Deal +50% more damage / Basic Attack heal 50 health on Hit',0),
(55,'Bramble Vest',"Negates bonus damage from incoming critical hits. On being hit by a Basic Attack deal 100 / 140 / 200 magic damage to all nearby enemies (once every 2.5 second maximum). Scales with wearer's Star Level.",0),
(56,'Sword Breaker','25% chance to disarm for 3 seconds',0),
(57,'Red Buff','Gains 30% max hp true damage over 10 seconds on hit in addition to its burn. And reducing healing by 50% for the duration of the burn.',0),
(58,'Rebel Medal','The wearer gains the Rebel trait',0),
(59,'Shroud of Stillness',"When combat begins shoots a beam straight ahead that delays affected enemies' first spellcast increasing their max Mana by 40% until they cast",0),
(66,"Dragon's Claw",'Reduces incoming magic damage by 50%',0),
(67,'Zephyr','When combat begins the wearer summons a whirlwind on the opposite side of the arena that removes the closest enemy from combat for 5 seconds',0),
(68,'Celestial Orb','The wearer gains the Celestial trait',0),
(69,'Quicksilver','[UNIQUE] The wearer is immute to croud control for the first 15 seconds of combat',0),
(77,"Warmog's Armor",'Grants 1000 total health',0),
(78,"Protector's Chestguard",'The wearer gains the Protector trait',0),
(79,'Trap Claw','Start combat with a spell shield. Stun the champion that breaks it for 4 sec.',0),
(88,'Force of Nature','Gain +1 team size',0),
(89,"Dark Star's Heart",'The wearer gains the Dark Star trait', 0),
(99,"Thief's Gloves",'Each planning phase fetch two temporary items, quality based upon your player level. [Consumes Three item Slots]',0);

create table items2(
	item_id int(3) unsigned primary key,
	stat_1 varchar(20),
    stat_2 varchar(20));
insert into items2
values(1,'+(15 Attack Damage',null),
(2,'+(15% Attack Speed',null),
(3,'+20% Ability Power',null),
(4,'+20 Starting Mana',null),
(5,'+25 Armor',null),
(6,'+25 Magic Resist',null),
(7,'+200 Health',null),
(8, null, null),
(9,'+10% Dodge Chance','+10% Crit Chance'),
(11,'+30 Attack Damage',null),	
(12,'+15 Attack Damage','+15% Attack Speed'),
(13,'+15 Attack Damage','+20% Ability Power'),
(14,'+15 Attack Damage','+20 Starting Mana'),
(15,'+15 Attack Damage','+25 Armor'),
(16,'+15 Attack Damage','+25 Magic Resist'),
(17,'+15 Attack Damage','+200 Health'),
(18,'+15 Attack Damage',null),
(19,'+15 Attack Damage','+20% Crit Chance'),
(22,'+30% Attack Speed',null),
(23,'+15% Attack Speed','+20% Ability Power'),
(24,'+15% Attack Speed','+20 Starting Mana'),
(25,'+15% Attack Speed','+25 Armor'),
(26,'+15% Attack Speed','+25 Magic Resist'),
(27,'+15% Attack Speed','+200 Health'),
(28,'+15% Attack Speed',null),
(29,'+15% Attack Speed','+20% Crit Chance'),
(33,'+40% Ability Power',null),
(34,'+20% Ability Power','+20 Starting Mana'),
(35,'+20% Ability Power','+25 Armor'),
(36,'+20% Ability Power','+25 Magic Resist'),
(37,'+20% Ability Power','+200 Health'),
(38,'+20% Ability Power',null),
(39,'+20% Ability Power','+20% Crit Chance'),
(44,'+40 Starting Mana',null),
(45,'+20 Starting Mana','+25 Armor'),
(46,'+20 Starting Mana','+25 Magic Resist'),
(47,'+20 Starting Mana','+200 Health'),
(48,'+20 Starting Mana',null),
(49,'+20 Starting Mana','+20% Crit Chance'),
(55,'+50 Armor',null),
(56,'+25 Armor','+25 Magic Resist'),
(57,'+25 Armor','+200 Health'),
(58,'+25 Armor',null),
(59,'+25 Armor','+20% Dodge Chance'),
(66,'+50 Magic Resist',null),
(67,'+25 Magic Resist','+200 Health'),
(68,'+25 Magic Resist',null),
(69,'+25 Magic Resist','+20% Dodge Chance'),
(77,'+400 Health',null),
(78,'+200 Health',null),
(79,'+200 Health','+20% Dodge Chance'),
(88, null, null),
(89,'+10% Dodge Chance','+10% Crit Chance'),
(99,'+20% Dodge Chance','+20% Crit Chance');